### ISSUE TITLE
pricing plan veliu da letter spacing berilishi kerak edi

### ISSUE THREAD

**Issue by Sardorbek-Raximberdiyev** [kamolazohidova/Zk_Pricing-component#1]
![image](https://user-images.githubusercontent.com/99403792/166107512-596fcca9-3cca-4322-b900-516945bf3afd.png)
-2px letter spacing berib qoyish kerak

**Comment by kamolazohidova** [comment]
qo'shsam ham farqi bolmadida shunga olib tashlagandim☹
