### ISSUE TITLE
background img aniq joylashtirilmagan 

### ISSUE THREAD

**Issue by Sardorbek-Raximberdiyev** [kamolazohidova/Zk_Pricing-component#2]
![image](https://user-images.githubusercontent.com/99403792/166107580-8813afd3-a489-418c-aa39-ba5f9718a69e.png)
100% da maketdagi joyida turmayapti

**Comment by kamolazohidova** [comment]
aniq o'lchami bormidi anqmas deyapsz🙄😏😑
