### ISSUE TITLE
`pricing-plan` qismidagi linklarga `active` holati berilmagan

### ISSUE THREAD

**Issue by darxanov** [kamolazohidova/Zk_Pricing-component#3]
![image](https://user-images.githubusercontent.com/99054718/166107720-9feeef07-73a9-475a-bc86-297374a9366a.png)

Bu linklar `active` holatidi bu rasmdagidek bo'lishi kerak: 
![image](https://user-images.githubusercontent.com/99054718/166107767-d5ca10e6-cf3d-4002-a221-a0b65491851b.png)

Active holati stillari maketda berilgan!

**Comment by kamolazohidova** [comment]
qo'shildi🙂
