### ISSUE TITLE
Ikkinchi (professional) bolimdagi tugma hover bo'lganda background color transporent bolishi kerak

### ISSUE THREAD

**Issue by Sardorbek-Raximberdiyev** [kamolazohidova/Zk_Pricing-component#4]
![image](https://user-images.githubusercontent.com/99403792/166107776-2b9b82d8-a988-475e-b4e7-f73f5e70b7df.png)
![image](https://user-images.githubusercontent.com/99403792/166107783-d432a598-a319-42cf-b5cc-4bf081b4c091.png)
chunki tugma  chapdan o'nga qaragan rangi to'qlashib boradi

**Comment by kamolazohidova** [comment]
hop
