### ISSUE TITLE
CSS kodini validatorda tekshirganda chiqgan xatolarni to'g'irlash kerak

### ISSUE THREAD

**Issue by darxanov** [kamolazohidova/Zk_Pricing-component#6]
![image](https://user-images.githubusercontent.com/99054718/166107876-28769a3c-e0dc-427c-a40f-ae0b00b382bc.png)

CSS kodni validatorda tekshirilganida bitta error chiqdi, shuni to'g'irlash kerak, bu yerda xatoning mazmuni shundan iborat:

CSSda `align-items` hossasiga rang berilgan va bu hossaga rang berish xato hisoblanadi. 141-qatordagi bu hossaga o'z qiymatini berish kerak, rasmda ko'rsatilgan: 
![image](https://user-images.githubusercontent.com/99054718/166107951-8ee053a8-f8f2-4b49-8fa4-1bcfda23bbf6.png)

**Comment by kamolazohidova** [comment]
uzuriya🙃
