### ISSUE TITLE
bo'limlarga berilgan paddinglar kattaligi sababli o'zi(bo'limlar)ning o'lchami katta bo'lib ketyapti

### ISSUE THREAD

**Issue by Sardorbek-Raximberdiyev** [kamolazohidova/Zk_Pricing-component#7]
![image](https://user-images.githubusercontent.com/99403792/166108054-ce7bed0e-5c19-43d0-9e0f-25568f555a13.png)
padding 31px bolishi kerak

**Comment by kamolazohidova** [comment]
to'g'irlaymiz👌
