### ISSUE TITLE
pricing plan value dagi rang xato berilgan 

### ISSUE THREAD

**Issue by Sardorbek-Raximberdiyev** [kamolazohidova/Zk_Pricing-component#8]
![image](https://user-images.githubusercontent.com/99403792/166116250-28bd39db-5b5c-454a-9633-b37fa99fe840.png)
aslida bunaqa  bo'lishi kerak
![image](https://user-images.githubusercontent.com/99403792/166116264-8389cd2d-8084-404b-9066-8502bd2c8619.png)

**Comment by kamolazohidova** [comment]
xazillashgandim🙃🤪
